article: https://www.hackster.io/jakub-smejkal/wireless-presenter-with-accelerometer-962318
video: https://youtu.be/OCPPKXzCBg0
images:
  - title:
    url: https://raw.githubusercontent.com/hardwario/website/master/static/kits-images/push-button/main.png
assembly:
  - name: HARDWARIO Button Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
